// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("http://localhost:8000/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.linkText("toDo.html")).click();
    driver.findElement(By.cssSelector(".input-text")).click();
    driver.findElement(By.cssSelector(".input-text")).sendKeys("This is the first job");
    driver.findElement(By.cssSelector(".input-text")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".input-text")).sendKeys("This is the second job");
    driver.findElement(By.cssSelector(".btn-warning")).click();
    driver.findElement(By.cssSelector(".list-items:nth-child(1) input")).click();
    driver.findElement(By.cssSelector(".list-items:nth-child(1) input")).click();
    driver.findElement(By.cssSelector(".list-items:nth-child(2) input")).click();
    driver.findElement(By.cssSelector(".list-items:nth-child(2) input")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".list-items:nth-child(2) .btn-del")).click();
    driver.findElement(By.cssSelector(".input-text")).click();
    driver.findElement(By.cssSelector(".input-text")).sendKeys("This is another job");
    driver.findElement(By.cssSelector(".input-text")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".list-items:nth-child(1) input")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".input-text")).click();
    driver.findElement(By.cssSelector(".input-text")).sendKeys("This is the last job");
    driver.findElement(By.cssSelector(".btn-warning")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-warning"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".list-items:nth-child(2) input")).click();
    driver.findElement(By.cssSelector(".list-items:nth-child(1) input")).click();
    driver.findElement(By.cssSelector(".list-items:nth-child(1) input")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
  }
}
